NEW = 'NEW'
IN_DISCUSSION = 'IN_DISCUSSION'
REJECTED = 'REJECTED'
IN_PROGRESS = 'IN_PROGRESS'
FULFILLED = 'FULFILLED'
TICKET_STATUS_ENUM = [NEW, IN_DISCUSSION, REJECTED, IN_PROGRESS, FULFILLED] 
NEXT_STATES = {
        'NEW': ['IN_PROGRESS', 'IN_DISCUSSION'],
        'IN_PROGRESS': ['FULFILLED', 'IN_DISCUSSION'],
        'IN_DISCUSSION': ['IN_PROGRESS', 'REJECTED'],
        'REJECTED': [],
        'FULFILLED': []
    }